### ISSUE TITLE
Udemy should be removed

### ISSUE THREAD

**Issue by dakira** [QtRoS/academy#6]
Udemy is fraudulent company and should not be featured in this app. Google "udemy stolen content" for background. Here are some news articles:
- [Anger at ‘stolen’ online courses on Udemy](http://www.bbc.com/news/technology-34952382)
- [The piracy paradox at Udemy](http://www.troyhunt.com/2015/11/the-piracy-paradox-at-udemy.html)
- [Pirated Courses on Udemy](https://news.ycombinator.com/item?id=10638795)

Usually people rip off other peoples (often free) content, post it on Udemy, Udemy collects the money and pays out the thief. Jeffrey Way, the creator of laracasts.com was finally able to get in touch with them and asked about the money the already collected. There only reply was "go ahead and sue us." which he of course doesn't have the resources for.

So these people are evil scumbags you don't at all want to be associated with.

**Comment by QtRoS** [comment]
Problem is not in service itself, but in people's nature. These people behave badly when they are stoling courses. But what can service do? It's their money.

Standalone example: Canonical should remove Telegram app from Ubuntu Phone because it uses encryption. Terrorists can use it in their activity. Are you agree?

**Comment by dakira** [comment]
Its Udemy who's keeping the money that they earned from other peoples content. Their reaction is "so what? Sue us if you want."

Two better reactions would be to either pay the money back to the course subscribers or pay the profits to the original creator. Udemy is the only course platform that is widely known for this practice.

So to clarify: The problem **is** in the service and **not** in the people. There are always people submitting stolen content. That is not the problem. The problem is how Udemy **keeps** the money the subscribers payed for the courses instead of giving it back. That makes them frauds.

I just wanted to let you know that you are supporting fraudsters by having them in your app because I thought you might care.

**Comment by QtRoS** [comment]
My opinion - no one can be good for everyone. Sometimes Google, Apple or Microsoft are bad too. 
Solution - switch off "Udemy" source in options!

Anyway - thanks for your opinion, I will take a deeper look ;)

**Comment by dakira** [comment]
> My opinion - no one can be good for everyone

Yeah, that's true of course. I just think the Udemy people are really big a*holes and I hate to see them featured and promoted within the Ubuntu community.
